variables:
  CBI_NODE_VERSION: 'node:12-alpine'
  CBI_MAJOR_VERSION: 11
  CBI_MINOR_VERSION: 9

include:
  - project: 'engineering/gitlab-includes'
    ref: latest
    file: 'npm-login.yml'

  - project: 'engineering/gitlab-includes'
    ref: latest
    file: 'front-end-build-yarn.yml'

  - project: 'engineering/gitlab-includes'
    ref: latest
    file: 'front-end-test-yarn.yml'

  - project: 'engineering/gitlab-includes'
    ref: latest
    file: 'front-end-publish-npm.yml'

type-check:
  retry: 2
  stage: test
  script:
    - yarn type-check
  tags:
    - shell
    - dev
  except:
    - tags

stages:
  - configure
  - authenticate
  - build
  - test
  - publish
