on:
  pull_request:
    branches: ['master']
  push:
    branches: ['master']

jobs:
  test:
    uses: cbinsights/form-design-system/.github/workflows/test.yml@master
  typecheck:
    uses: cbinsights/form-design-system/.github/workflows/typecheck.yml@master
  linting:
    uses: cbinsights/form-design-system/.github/workflows/linting.yml@master
