name: Pull request

on:
  pull_request:
    branches: ['master']

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
  typecheck:
    uses: ./.github/workflows/reusable-typecheck.yml
  lint:
    uses: ./.github/workflows/reusable-linting.yml
  e2e-test:
    uses: ./.github/workflows/reusable-e2e-test.yml
