name: NPM publish reusable workflow

on:
  workflow_call:

jobs:
  test:
    uses: cbinsights/form-design-system/.github/workflows/reusable-test.yml@master
  typecheck:
    uses: cbinsights/form-design-system/.github/workflows/reusable-typecheck.yml@master
  lint:
    uses: cbinsights/form-design-system/.github/workflows/reusable-linting.yml@master
  npm-beta:
    name: Publish npm beta version
    needs: [test, typecheck, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org/'
          always-auth: true
          scope: '@cbinsights'
      - name: Yarn Install
        run: yarn --frozen-lockfile
      - name: Build Style Dictionary
        run: yarn build
      - run: git config --global user.email "noreply@cbinsights.com"
      - run: git config --global user.name "CBI Github CI"
      - run: yarn publish --new-version 11.11.${GITHUB_RUN_ID}-beta.${GITHUB_SHA::8} --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
