name: Node.js CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: yarn build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: yarn test
